name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GOLANGCI_LINT_VERSION: "v2.2.1"

jobs:
  build:
    strategy:
      matrix:
        go-version: ['1.24' ]
        os: [ ubuntu-24.04, macos-14, windows-2022 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: |
            **/go.sum
            **/go.mod

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enforce standard format
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --verbose

      - name: Test
        run: go test --cover -v ./...

      - name: Build
        run: go build -v ./...
